// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFK-0uOzmNeCOOz5nEu7lCjElHlX4RtNQ',
    appId: '1:44175476464:web:e2032bba714fbb28e16435',
    messagingSenderId: '44175476464',
    projectId: 'flutter-app-226f9',
    authDomain: 'flutter-app-226f9.firebaseapp.com',
    storageBucket: 'flutter-app-226f9.appspot.com',
    measurementId: 'G-TF6KZ5K7YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPInHkgTE4I5FmPakSF3MJRcd_JqhJh0o',
    appId: '1:44175476464:android:d61889b10271100be16435',
    messagingSenderId: '44175476464',
    projectId: 'flutter-app-226f9',
    storageBucket: 'flutter-app-226f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCum39GueCh9sGl0WhYasS_5WM2MWNBJ5E',
    appId: '1:44175476464:ios:6bad7b5e62353360e16435',
    messagingSenderId: '44175476464',
    projectId: 'flutter-app-226f9',
    storageBucket: 'flutter-app-226f9.appspot.com',
    iosClientId: '44175476464-qu1tv189a46m6jbpaf2k3abgn9t86frt.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCum39GueCh9sGl0WhYasS_5WM2MWNBJ5E',
    appId: '1:44175476464:ios:063d9fccf4f8e282e16435',
    messagingSenderId: '44175476464',
    projectId: 'flutter-app-226f9',
    storageBucket: 'flutter-app-226f9.appspot.com',
    iosClientId: '44175476464-b2rrhucu31u76q4vq66qutnafj4k7lc7.apps.googleusercontent.com',
    iosBundleId: 'com.example.practice.RunnerTests',
  );
}
